/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tnandpl.gui;

import tnandpl.gui.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import tnandpl.pojo.CurrentUser;

/**
 *
 * @author Dell
 */
public class AdminOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionsFrame
     */
    public AdminOptionsFrame() {
       
        initComponents();
        jp1.setSize(800,500);
         this.setLocationRelativeTo(null);
        jlblgetName.setText(CurrentUser.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jp1 = new javax.swing.JPanel();
        jlblMap = new javax.swing.JLabel();
        jlblWelcome = new javax.swing.JLabel();
        jbtnHrModule = new javax.swing.JButton();
        btnViewAllJobs = new javax.swing.JButton();
        btnViewAllStudents = new javax.swing.JButton();
        btnSelectedStudents = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlblgetName = new javax.swing.JLabel();
        jbtnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jp1.add(jlblMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 760, 110));

        jlblWelcome.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jlblWelcome.setText("Welcome, ");
        jp1.add(jlblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 30));

        jbtnHrModule.setBackground(java.awt.SystemColor.activeCaption);
        jbtnHrModule.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnHrModule.setText("HR Mudoule"); // NOI18N
        jbtnHrModule.setFocusPainted(false);
        jbtnHrModule.setFocusable(false);
        jbtnHrModule.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnHrModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHrModuleActionPerformed(evt);
            }
        });
        jp1.add(jbtnHrModule, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 250, 30));

        btnViewAllJobs.setBackground(java.awt.SystemColor.activeCaption);
        btnViewAllJobs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnViewAllJobs.setText("View All Jobs");
        btnViewAllJobs.setFocusPainted(false);
        btnViewAllJobs.setFocusable(false);
        btnViewAllJobs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewAllJobs.setOpaque(false);
        btnViewAllJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllJobsActionPerformed(evt);
            }
        });
        jp1.add(btnViewAllJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 250, 30));

        btnViewAllStudents.setBackground(java.awt.SystemColor.activeCaption);
        btnViewAllStudents.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnViewAllStudents.setText("View All Students");
        btnViewAllStudents.setFocusPainted(false);
        btnViewAllStudents.setFocusable(false);
        btnViewAllStudents.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllStudentsActionPerformed(evt);
            }
        });
        jp1.add(btnViewAllStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 250, 30));

        btnSelectedStudents.setBackground(java.awt.SystemColor.activeCaption);
        btnSelectedStudents.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSelectedStudents.setText("View Selected Students");
        btnSelectedStudents.setFocusPainted(false);
        btnSelectedStudents.setFocusable(false);
        btnSelectedStudents.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSelectedStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectedStudentsActionPerformed(evt);
            }
        });
        jp1.add(btnSelectedStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 250, 30));

        jButton1.setBackground(java.awt.SystemColor.activeCaption);
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Logout");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jp1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 120, 30));

        jLabel1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mylogo3.png"))); // NOI18N
        jp1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        jlblgetName.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jp1.add(jlblgetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 280, 30));

        jbtnBack.setBackground(java.awt.SystemColor.activeCaption);
        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        jp1.add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/purepng.com-white-paper-planpaper-planeaeroplanepaper-gliderpaper-dartaircraftfolded-paperpaperboardclipartblack-1421526588279c5fht (1).png"))); // NOI18N
        jp1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 320, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new LoginFrame().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnHrModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHrModuleActionPerformed
     new AdminHrModuleFrame().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jbtnHrModuleActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
          new LoginFrame().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void btnViewAllJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllJobsActionPerformed
        new AdminViewAllJobsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewAllJobsActionPerformed

    private void btnViewAllStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllStudentsActionPerformed
        new AdminViewAllStudentsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewAllStudentsActionPerformed

    private void btnSelectedStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectedStudentsActionPerformed
      new AdminViewAllSelectedStudentsFrame().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnSelectedStudentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectedStudents;
    private javax.swing.JButton btnViewAllJobs;
    private javax.swing.JButton btnViewAllStudents;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnHrModule;
    private javax.swing.JLabel jlblMap;
    private javax.swing.JLabel jlblWelcome;
    private javax.swing.JLabel jlblgetName;
    private javax.swing.JPanel jp1;
    // End of variables declaration//GEN-END:variables
}
