/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tnandpl.gui;

import tnandpl.gui.*;
import tnandpl.pojo.CurrentUser;

/**
 *
 * @author Dell
 */
public class AdminHrModuleFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminHrModuleFrame
     */
    public AdminHrModuleFrame() {
        initComponents();
        jp1.setSize(800,500);
        this.setLocationRelativeTo(null);
        jlblName.setText(CurrentUser.getName());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnAddNewHr = new javax.swing.JButton();
        jbtnRemoveHr = new javax.swing.JButton();
        jbtnModifyHr = new javax.swing.JButton();
        jbtnShowAllHr = new javax.swing.JButton();
        jbtnLogout = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jp1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 760, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mylogo3.png"))); // NOI18N
        jp1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        jLabel3.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel3.setText("WELCOME  ,");
        jp1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        jlblName.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jp1.add(jlblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 250, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNewEmp.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 150));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 150));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 120));
        jp1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Remove-Emp.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 120));
        jLabel5.setMinimumSize(new java.awt.Dimension(120, 120));
        jp1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 160, 130));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modify-emp.png"))); // NOI18N
        jp1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 140, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewAllHr.png"))); // NOI18N
        jp1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 170, 140));

        jbtnAddNewHr.setBackground(java.awt.SystemColor.activeCaption);
        jbtnAddNewHr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnAddNewHr.setText("Add New HR");
        jbtnAddNewHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewHrActionPerformed(evt);
            }
        });
        jp1.add(jbtnAddNewHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 150, 25));

        jbtnRemoveHr.setBackground(java.awt.SystemColor.activeCaption);
        jbtnRemoveHr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnRemoveHr.setText("Remove HR");
        jbtnRemoveHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveHrActionPerformed(evt);
            }
        });
        jp1.add(jbtnRemoveHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 150, 25));

        jbtnModifyHr.setBackground(java.awt.SystemColor.activeCaption);
        jbtnModifyHr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnModifyHr.setText("Modify HR");
        jbtnModifyHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModifyHrActionPerformed(evt);
            }
        });
        jp1.add(jbtnModifyHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 150, 25));

        jbtnShowAllHr.setBackground(java.awt.SystemColor.activeCaption);
        jbtnShowAllHr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnShowAllHr.setText("View All HR");
        jbtnShowAllHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowAllHrActionPerformed(evt);
            }
        });
        jp1.add(jbtnShowAllHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 150, 25));

        jbtnLogout.setBackground(java.awt.SystemColor.activeCaption);
        jbtnLogout.setText("Logout");
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });
        jp1.add(jbtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 120, 25));

        jbtnBack.setBackground(java.awt.SystemColor.activeCaption);
        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        jp1.add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 120, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
    new AdminOptionsFrame().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
      new LoginFrame().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jbtnLogoutActionPerformed

    private void jbtnAddNewHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNewHrActionPerformed
       new AdminAddNewHrFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jbtnAddNewHrActionPerformed

    private void jbtnShowAllHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowAllHrActionPerformed
         new AdminViewAllHrFrame().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jbtnShowAllHrActionPerformed

    private void jbtnModifyHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModifyHrActionPerformed
      new AdminModifyHrFrame().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jbtnModifyHrActionPerformed

    private void jbtnRemoveHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveHrActionPerformed
       new AdminRemoveHrFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jbtnRemoveHrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHrModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHrModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHrModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHrModuleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHrModuleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnAddNewHr;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnLogout;
    private javax.swing.JButton jbtnModifyHr;
    private javax.swing.JButton jbtnRemoveHr;
    private javax.swing.JButton jbtnShowAllHr;
    private javax.swing.JLabel jlblName;
    private javax.swing.JPanel jp1;
    // End of variables declaration//GEN-END:variables
}
