/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tnandpl.gui;

import tnandpl.gui.*;
import tnandpl.pojo.CurrentUser;

/**
 *
 * @author Dell
 */
public class HrJobOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form HrJobModuleFrame
     */
    public HrJobOptionsFrame() {
        initComponents();
         this.setLocationRelativeTo(null);
        lblName.setText(CurrentUser.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnAddJob = new javax.swing.JButton();
        jbtnRemoveJob = new javax.swing.JButton();
        jbtnEditJob = new javax.swing.JButton();
        jbtnSetQuiz = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 760, 120));

        jLabel2.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel2.setText("WELCOME ,");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 40));

        lblName.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New/istockphoto-1285196602-612x612 (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New/removeJob (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 150, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New/editJob.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 160, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New/setQuiz.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 170, 120));

        jbtnAddJob.setBackground(java.awt.SystemColor.activeCaption);
        jbtnAddJob.setText("Add New Job");
        jbtnAddJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddJobActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAddJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 150, 25));

        jbtnRemoveJob.setBackground(java.awt.SystemColor.activeCaption);
        jbtnRemoveJob.setText("Remove Job");
        jbtnRemoveJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveJobActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRemoveJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 150, 25));

        jbtnEditJob.setBackground(java.awt.SystemColor.activeCaption);
        jbtnEditJob.setText("Edit Job");
        jbtnEditJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditJobActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEditJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 150, 25));

        jbtnSetQuiz.setBackground(java.awt.SystemColor.activeCaption);
        jbtnSetQuiz.setText("Set Quiz");
        jbtnSetQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSetQuizActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSetQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 150, 25));

        jbtnBack.setBackground(java.awt.SystemColor.activeCaption);
        jbtnBack.setText("BACK");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 120, 25));

        jbtnLogout.setBackground(java.awt.SystemColor.activeCaption);
        jbtnLogout.setText("LOGOUT");
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 120, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
      new HrOptionsFrame().setVisible(true);  
       this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnLogoutActionPerformed

    private void jbtnAddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddJobActionPerformed
          new HrAddNewJobFrame().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jbtnAddJobActionPerformed

    private void jbtnRemoveJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveJobActionPerformed
          new HrRemoveJobFrame().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jbtnRemoveJobActionPerformed

    private void jbtnEditJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditJobActionPerformed
       new HrChooseJobForEditFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jbtnEditJobActionPerformed

    private void jbtnSetQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSetQuizActionPerformed
        new HrQuizOptionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnSetQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrJobOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrJobOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrJobOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrJobOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrJobOptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAddJob;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnEditJob;
    private javax.swing.JButton jbtnLogout;
    private javax.swing.JButton jbtnRemoveJob;
    private javax.swing.JButton jbtnSetQuiz;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
